# Generated by Django 3.2.18 on 2023-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_closelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(default='active', max_length=7),
        ),
    ]
